name: Run Tests
on push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Bun.js
              uses: actions/setup-bun@v1
              with:
                  node-version: "16"
            - name: Install dependencies
              run: bun install
            - name: Run tests
              run: bun test
deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Bun.js
          uses: oven-sh/setup-bun@v1
          with:
              bun-version: "1.0.0"
        - name: Install dependencies
          run: bun install
        - name: Deploy to Vercel
          run: bnx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
          env:
              VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
              VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}